package front;

import control.*;
import java.text.DecimalFormat;

import javax.swing.*;
import model.Configuracion;

public class VentanaPrincipal extends javax.swing.JFrame {

    private Controller controlador;
    private DecimalFormat formato = new DecimalFormat("0.00");
    
    
    public VentanaPrincipal(Controller controlador) {
        this.controlador = controlador;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Simulación por Colas - Ejercicio N°5: Biblioteca");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelConfiguracion = new javax.swing.JPanel();
        gpb_consultas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_consulta_desde = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_consulta_hasta = new javax.swing.JTextField();
        jPanelParametros = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_promPermanencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_llegada_cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_tiempo_sim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_cantidad_sim = new javax.swing.JTextField();
        jPanelRango = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_rango_desde = new javax.swing.JTextField();
        txt_rango_hasta = new javax.swing.JTextField();
        jPanelProb = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProbPostAtencion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProbConsulta = new javax.swing.JTable();
        jScrollPaneSimulacion = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelResultados = new javax.swing.JPanel();
        btn_simular = new javax.swing.JButton();
        btn_resetSim = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();

        gpb_consultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuracion inicial", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        gpb_consultas.setBorder(javax.swing.BorderFactory.createTitledBorder("Distribucion Consultas"));

        jLabel7.setText("Desde:");

        jLabel8.setText("Hasta: ");

        javax.swing.GroupLayout gpb_consultasLayout = new javax.swing.GroupLayout(gpb_consultas);
        gpb_consultas.setLayout(gpb_consultasLayout);
        gpb_consultasLayout.setHorizontalGroup(
            gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gpb_consultasLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_consulta_desde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_consulta_hasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        gpb_consultasLayout.setVerticalGroup(
            gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gpb_consultasLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_consulta_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(gpb_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_consulta_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22))
        );

        jPanelParametros.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabel9.setText("Promedio de permanencia: ");

        txt_promPermanencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_promPermanenciaActionPerformed(evt);
            }
        });

        jLabel6.setText("Tiempo llegada entre clientes:");

        jLabel10.setText("Tiempo de simulacion:");

        jLabel11.setText("Cantidad de simulaciones:");

        jPanelRango.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar entre"));

        jLabel1.setText("Rango desde:");

        jLabel2.setText("Rango hasta:");

        javax.swing.GroupLayout jPanelRangoLayout = new javax.swing.GroupLayout(jPanelRango);
        jPanelRango.setLayout(jPanelRangoLayout);
        jPanelRangoLayout.setHorizontalGroup(
            jPanelRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRangoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_rango_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_rango_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        jPanelRangoLayout.setVerticalGroup(
            jPanelRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRangoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txt_rango_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rango_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanelParametrosLayout = new javax.swing.GroupLayout(jPanelParametros);
        jPanelParametros.setLayout(jPanelParametrosLayout);
        jPanelParametrosLayout.setHorizontalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelParametrosLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_cantidad_sim, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelParametrosLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tiempo_sim, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelParametrosLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_llegada_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelParametrosLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(41, 41, 41)
                            .addComponent(txt_promPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanelParametrosLayout.setVerticalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelParametrosLayout.createSequentialGroup()
                        .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_promPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_llegada_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tiempo_sim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cantidad_sim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jPanelRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanelProb.setBorder(javax.swing.BorderFactory.createTitledBorder("Probabilidades"));

        jTableProbPostAtencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Se retira", "", ""},
                {"Se queda", "", ""}
            },
            new String [] {
                "Post Atencion", "Probabilidad", "Probabilidad Acumulada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProbPostAtencion);

        jTableProbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pedido de libros", "", ""},
                {"Devolucion de libros", "", ""},
                {"Consulta ", "", ""}
            },
            new String [] {
                "Tipo de Atencion", "Probabilidad", "Probabilidad Acumulada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableProbConsulta);

        javax.swing.GroupLayout jPanelProbLayout = new javax.swing.GroupLayout(jPanelProb);
        jPanelProb.setLayout(jPanelProbLayout);
        jPanelProbLayout.setHorizontalGroup(
            jPanelProbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProbLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanelProbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanelProbLayout.setVerticalGroup(
            jPanelProbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProbLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanelConfiguracionLayout = new javax.swing.GroupLayout(jPanelConfiguracion);
        jPanelConfiguracion.setLayout(jPanelConfiguracionLayout);
        jPanelConfiguracionLayout.setHorizontalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addComponent(jPanelProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(gpb_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanelConfiguracionLayout.setVerticalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanelProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpb_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configuracion", jPanelConfiguracion);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSimulacion.setViewportView(jTable1);

        jTabbedPane1.addTab("Simulacion", jScrollPaneSimulacion);

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Resultados", jPanelResultados);

        btn_simular.setText("Simular");

        btn_resetSim.setText("Eliminar Simulacion");
        btn_resetSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetSimActionPerformed(evt);
            }
        });

        btn_configuracion.setText("Setear configuracion por defecto");
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btn_resetSim, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_configuracion)
                .addGap(20, 20, 20)
                .addComponent(btn_simular, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_resetSim)
                    .addComponent(btn_simular)
                    .addComponent(btn_configuracion))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        btn_configuracion.getAccessibleContext().setAccessibleName("Setear configuración por defecto");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetSimActionPerformed
        limpiarSimulacion();
    }//GEN-LAST:event_btn_resetSimActionPerformed

    
    private void limpiarSimulacion(){
        txt_promPermanencia.setText("");
        txt_tiempo_sim.setText("");
        txt_cantidad_sim.setText("");
        txt_consulta_desde.setText("");
        txt_consulta_hasta.setText("");
        txt_llegada_cliente.setText("");
        txt_rango_desde.setText("");
        txt_rango_hasta.setText("");
        jTableProbConsulta.setValueAt("", 0, 1);
        jTableProbConsulta.setValueAt("", 0, 2);
        jTableProbConsulta.setValueAt("", 1, 1);
        jTableProbConsulta.setValueAt("", 1, 2);
        jTableProbConsulta.setValueAt("", 2, 1);
        jTableProbConsulta.setValueAt("", 2, 2);
        jTableProbPostAtencion.setValueAt("", 0, 1);
        jTableProbPostAtencion.setValueAt("", 0, 2);
        jTableProbPostAtencion.setValueAt("", 1, 1);
        jTableProbPostAtencion.setValueAt("", 1, 2);
    }
    
    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
        Configuracion config = Configuracion.getConfiguracion();
        txt_promPermanencia.setText("" + config.getPromedioPermanencia());
        txt_tiempo_sim.setText("" + config.getTiempoSimulacion());
        txt_cantidad_sim.setText("" + config.getCantidadSimulacion());
        txt_consulta_desde.setText("" + config.getConsultaDesde());
        txt_consulta_hasta.setText("" + config.getConsultaHasta());
        txt_llegada_cliente.setText("" + config.getLlegadaCliente());
        txt_rango_desde.setText("" + config.getRangoDesde());
        txt_rango_hasta.setText("" + config.getRangoHasta());
        jTableProbConsulta.setValueAt(formato.format(0.45), 0, 1);
        jTableProbConsulta.setValueAt(formato.format(0.45), 0, 2);
        jTableProbConsulta.setValueAt(formato.format(0.45), 1, 1);
        jTableProbConsulta.setValueAt(formato.format(0.90), 1, 2);
        jTableProbConsulta.setValueAt(formato.format(0.10), 2, 1);
        jTableProbConsulta.setValueAt(formato.format(1.00), 2, 2);
        jTableProbPostAtencion.setValueAt(formato.format(0.60), 0, 1);
        jTableProbPostAtencion.setValueAt(formato.format(0.60), 0, 2);
        jTableProbPostAtencion.setValueAt(formato.format(0.40), 1, 1);
        jTableProbPostAtencion.setValueAt(formato.format(1.00), 1, 2);
    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void txt_promPermanenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_promPermanenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_promPermanenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_resetSim;
    private javax.swing.JButton btn_simular;
    private javax.swing.JPanel gpb_consultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelConfiguracion;
    private javax.swing.JPanel jPanelParametros;
    private javax.swing.JPanel jPanelProb;
    private javax.swing.JPanel jPanelRango;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneSimulacion;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProbConsulta;
    private javax.swing.JTable jTableProbPostAtencion;
    private javax.swing.JTextField txt_cantidad_sim;
    private javax.swing.JTextField txt_consulta_desde;
    private javax.swing.JTextField txt_consulta_hasta;
    private javax.swing.JTextField txt_llegada_cliente;
    private javax.swing.JTextField txt_promPermanencia;
    private javax.swing.JTextField txt_rango_desde;
    private javax.swing.JTextField txt_rango_hasta;
    private javax.swing.JTextField txt_tiempo_sim;
    // End of variables declaration//GEN-END:variables
}
